---
title: "Stat 850 Project Description"
author: "Kyle Dougherty, Seth Norquest, Dalton Obermier"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(digits = 3)
```

## Instructions

Each member of your team should modify this document in some way and push their modifications to the repository in a separate commit. This will ensure that you have set your repository up in a way that ensures all group members are working with the same repository. 

Note that you must compile your readme (this document) for it to properly display as part of your github repository. 

Once you have received feedback on your project proposal (via Canvas) you may alter this README so that it describes your final project instead of the project proposal. 

## Data Set
https://github.com/stat850-unl/project-dalton-seth-kyle/blob/master/ST_project.xlsx
SowID = animal 
Treatment = Feeding time pre-farrow (1 = 7-10AM; 2 = 2-5AM)
Farrow Date = date of farrow, on a 1000 day calender
Onset = time of starting of farrowing
Piglet = number of piglets born when onset was recorded
End = completion of farrowing
Farrow Time = Duration of farrowing 
Induce = (1 = induced; 0 = not induced)
Due Date = 114 gestation date, on a 1000 day calender
Gestation length = gestation length
TNB = total number born 
SB = stillborn count 
SB_perc = stillborn percentage
## Potential Topics to Explore Using the Data Set
Describe avenues you might explore using the data

## Group Members


